version: '3'

services:
  darkbot:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    # All environment variables are loaded from .env file
    # These are just defaults that will be overridden by .env
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://localhost:27017
      - MONGODB_DATABASE=sneakerbot
      - MONGODB_COLLECTION=deals
      - EMAIL_NOTIFICATIONS=False
      - EMAIL_INTERVAL_MINUTES=30
