version: '3'

services:
  darkbot:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    # These environment variables will be overridden by .env
    environment:
      - PORT=8080
      - FLASK_ENV=production
      - STOCKX_API_KEY=
      - STOCKX_CLIENT_ID=
      - STOCKX_CLIENT_SECRET=
      - STOCKX_COOKIE=
      - FLASK_SECRET_KEY=
