"""
Package initialization for config.
"""

# Import and expose all configuration variables
from .config import (
    WEBSITES, MIN_DISCOUNT_PERCENT, BRANDS_OF_INTEREST,
    SAVE_TO_CSV, CSV_FILENAME, DATABASE_ENABLED, DATABASE_PATH,
    EMAIL_NOTIFICATIONS, EMAIL_INTERVAL_MINUTES, EMAIL_SERVER,
    EMAIL_PORT, EMAIL_ADDRESS, EMAIL_PASSWORD, EMAIL_RECIPIENT,
    HEADLESS_BROWSER, USE_SELENIUM, SCREENSHOT_ON_ERROR,
    MONGODB_ENABLED, MONGODB_CONNECTION_STRING, MONGODB_DATABASE, MONGODB_COLLECTION,
    CLOUDFLARE_R2_ENABLED, CLOUDFLARE_R2_ACCESS_KEY, CLOUDFLARE_R2_SECRET_KEY,
    CLOUDFLARE_R2_ENDPOINT, CLOUDFLARE_R2_BUCKET,
    USE_PROXY, PROXY_CONFIG
)

# Import site configurations
from .sites import SNEAKER_SITES, DEFAULT_SITES, MARKET_PRICE_SITES
